development:
  adapter: mysql2
  pool: 100
  timeout: 5000
  database: sns_push_dev
  username: root
  password: 
  reconnect: true
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: localhost

test:
  adapter: mysql2
  pool: 100
  timeout: 5000
  database: sns_push_dev
  username: root
  password: 
  reconnect: true
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: localhost

production:
  adapter: mysql2
  pool: 100
  timeout: 5000
  database: sns_push
  username: root
  password: 
  reconnect: true
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  host: localhost